In [29]:
import torch
import numpy as np

In [2]:
#1D vector with 3 elements
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [3]:
#2D matrix
x = torch.empty(2,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 2.1550e-14],
        [1.4013e-45,        nan, 0.0000e+00]])


In [4]:
#3D matrix
x = torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [5]:
#4D matrix
x = torch.empty(2,2,2,3)
print(x)

tensor([[[[1.4013e-44, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]],


        [[[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[0.0000e+00, 0.0000e+00, 0.0000e+00],
          [0.0000e+00, 0.0000e+00, 0.0000e+00]]]])


In [6]:
#tensor with random values
x = torch.rand(2,3)
x

tensor([[0.1545, 0.5412, 0.2547],
        [0.9662, 0.5861, 0.6257]])

In [7]:
#tensor with all zeros
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [8]:
#by default torch will be in float
x.dtype

torch.float32

In [9]:
#changing to other format
x = torch.ones(2,2, dtype=torch.int)
x

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [10]:
#size of tensor
x.size()

torch.Size([2, 2])

In [11]:
#tensor from python list
x = torch.tensor([1,2.3])
x

tensor([1.0000, 2.3000])

## Basic Operations of Tensors

In [12]:
x = torch.rand(2,3)
y = torch.rand(2,3)

In [13]:
print(x)
print(y)

tensor([[0.9496, 0.1488, 0.4991],
        [0.0047, 0.7385, 0.3413]])
tensor([[0.8307, 0.2648, 0.3971],
        [0.1173, 0.6212, 0.1402]])


In [14]:
#sum
z = x + y
z

tensor([[1.7802, 0.4136, 0.8962],
        [0.1220, 1.3596, 0.4816]])

In [15]:
#another way of adding
z = torch.add(x,y)
z

tensor([[1.7802, 0.4136, 0.8962],
        [0.1220, 1.3596, 0.4816]])

In [16]:
#can also do inplace addition (trailing underscore (_) is always inplace in pytorch) !!!
y.add_(x)
print(y)

tensor([[1.7802, 0.4136, 0.8962],
        [0.1220, 1.3596, 0.4816]])


In [17]:
#subtract
z = x - y 
#z = torch.sub(x,y)
z

tensor([[-0.8307, -0.2648, -0.3971],
        [-0.1173, -0.6212, -0.1402]])

In [18]:
#multiplication
z = torch.mul(x,y)
print(x)

tensor([[0.9496, 0.1488, 0.4991],
        [0.0047, 0.7385, 0.3413]])


In [19]:
#division
z = torch.div(x,y)
print(z)

tensor([[0.5334, 0.3597, 0.5569],
        [0.0383, 0.5431, 0.7088]])


##### All the operations above happens elementwise :)

### Slicing the tensor

In [20]:
#slicing in torch
x = torch.rand(5,3)
print(x)
print(x[:,1])
print(x[1,:])
print(x[1,1])

#if there is tensor with only one element, we can use .item() to retrieve the actual value
print(x[1,1].item())

tensor([[0.8994, 0.9301, 0.5184],
        [0.5416, 0.0575, 0.7610],
        [0.6401, 0.4765, 0.1166],
        [0.3873, 0.5879, 0.1661],
        [0.1986, 0.8870, 0.4515]])
tensor([0.9301, 0.0575, 0.4765, 0.5879, 0.8870])
tensor([0.5416, 0.0575, 0.7610])
tensor(0.0575)
0.05745077133178711


### Reshaping the tensor

In [24]:
x = torch.rand(4,4)
print(x)
print()
y = x.view(16)
print(y)
print(y.size())
print()
y = x.view(-1, 8)
print(y)
print(y.size())

tensor([[0.4106, 0.3963, 0.9147, 0.1384],
        [0.1638, 0.0565, 0.7471, 0.0635],
        [0.9962, 0.0039, 0.9119, 0.1237],
        [0.9958, 0.6509, 0.7697, 0.6472]])

tensor([0.4106, 0.3963, 0.9147, 0.1384, 0.1638, 0.0565, 0.7471, 0.0635, 0.9962,
        0.0039, 0.9119, 0.1237, 0.9958, 0.6509, 0.7697, 0.6472])
torch.Size([16])

tensor([[0.4106, 0.3963, 0.9147, 0.1384, 0.1638, 0.0565, 0.7471, 0.0635],
        [0.9962, 0.0039, 0.9119, 0.1237, 0.9958, 0.6509, 0.7697, 0.6472]])
torch.Size([2, 8])


In [25]:
y[0][0] = 1
print(y)

tensor([[1.0000, 0.3963, 0.9147, 0.1384, 0.1638, 0.0565, 0.7471, 0.0635],
        [0.9962, 0.0039, 0.9119, 0.1237, 0.9958, 0.6509, 0.7697, 0.6472]])


In [26]:
print(x)

tensor([[1.0000, 0.3963, 0.9147, 0.1384],
        [0.1638, 0.0565, 0.7471, 0.0635],
        [0.9962, 0.0039, 0.9119, 0.1237],
        [0.9958, 0.6509, 0.7697, 0.6472]])


In [28]:
### change in value of y also changes in x -> good to notice that

### Converting numpy to torch and vice versa

In [33]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [34]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

##### If the tensor is in CPU and not in GPU, both objects shares the same memory location, so changing one will also change the other. -> This is becoz numpy can handle only CPU tensors.

In [36]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [37]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [38]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [40]:
a += 1
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


#### If you see requires_grad=True in the code, it is specifying pytorch to calcualte the gradient in the optimization stage

In [41]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


## Operations if you have GPU and CPU

In [44]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device = device)
    
    y = torch.ones(5)
    y = y.to(device)
    
    z = x +y #operations in gpu
    
    z.numpy() #will show error as numpy can't handle gpu computations
    
    #if you want the gpu tensor back to numpy 
    z = z.to('cpu')
    z.numpy()